replicaCount: 4

image:
  repository: nginx
  tag: "1.27.123"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: nginx.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

pdb:
  enabled: true
  maxUnavailable: 1